name: shell commands

on: [push]

jobs:
   run-shell-command:
      runs-on: ubuntu-latest
      steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: echo sting
             run: echo "Hello"
          - name: multiline script
             run: |
                node -v
                pwd

   run-window-command: 
      runs-on: windows-latest
      steps:
          - name: Directory
            run: Get-location
          - name: Directory using bash
            run: pwd
            shell: bash              